# This is a title

## This is a subtitle

These are notes:

- Note 1
- Note 2

In [1]:
print("hello world")

hello world

# Task:

1. Download CSV files from my repo. 
2. Load them into this notebook using Pandas.
3. Clean the CSVs.
4. Output clean files.

# Pandas Demo

In [2]:
import pandas as pd

In [3]:
#Load data
# data = pd.read_csv("filepath")

data = {
    "name":["A", "B", "C"],
    "age":[25,26,27],
    "city":["London", "Manchester", "Coventry"]
}

df = pd.DataFrame(data)
df.head()

  name  age        city
0    A   25      London
1    B   26  Manchester
2    C   27    Coventry

In [6]:
#Useful Methods
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

        age
count   3.0
mean   26.0
std     1.0
min    25.0
25%    25.5
50%    26.0
75%    26.5
max    27.0

In [11]:
# Filter a certail col:
df["age"] #same as: df.age

df.age.mean()

26.0

In [ ]:
# Filtering rows
##[ROWS,COLS]

df.loc[df["city"] == "London", :] # : means everying

  name  age    city
0    A   25  London

In [14]:
# Creating a new col:
df["newCol"] = df.age + 10
df.head()

  name  age        city  newCol
0    A   25      London      35
1    B   26  Manchester      36
2    C   27    Coventry      37

In [ ]:
df2 = pd.read_csv("Data/03_Library Systembook.csv")
df2.head(n=10)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0